version: 2

project_name: static-webshot

builds:
  - main: ./cmd/staticwebshot
    binary: static-webshot
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version=v{{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
      - goos: windows
        goarch: arm64

archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: ['tar.gz']
    format_overrides:
      - goos: windows
        formats: ['zip']

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  use: github-native

release:
  name_template: "v{{ .Version }}"
  draft: false
  prerelease: auto

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"
